create type public.payment_status as enum (
  'unpaid',
  'processing',
  'paid',
  'failed',
  'refunded',
  'cancelled',
  'free'
);

create table public.conventions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  year bigint not null,
  name text null,
  start_date date null,
  end_date date null,
  location text null,
  constraint conventions_pkey primary key (id)
) TABLESPACE pg_default;

alter table public.conventions enable row level security;

create table public.badge_counters (
  convention_id bigint not null,
  badge_counter bigint not null default '0'::bigint,
  constraint badge_counters_pkey primary key (convention_id),
  constraint badge_counters_convention_id_fkey foreign KEY (convention_id) references conventions (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

alter table public.badge_counters enable row level security;

create table public.registrations (
  created_at timestamp with time zone not null default now(),
  ticket_type text not null,
  convention_id bigint not null,
  payment_status public.payment_status not null default 'unpaid'::payment_status,
  badge_id numeric null,
  user_id uuid not null,
  constraint registrations_pkey primary key (convention_id, user_id),
  constraint registrations_convention_id_fkey foreign KEY (convention_id) references conventions (id) on update CASCADE,
  constraint registrations_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

alter table public.registrations enable row level security;

create trigger badge_id_creator BEFORE INSERT on registrations for EACH row
execute FUNCTION set_badge_id ();

create table public.attendees (
  created_at timestamp with time zone not null default now(),
  first_name text not null,
  last_name text not null,
  phone text not null,
  pronouns text null,
  user_id uuid not null,
  nickname text null,
  dob timestamp without time zone null,
  emergency_contact_name text null,
  emergency_contact_phone text null,
  medical_info text null,
  fursuit text null,
  constraint attendees_pkey primary key (user_id),
  constraint attendees_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

alter table public.attendees enable row level security;